### ISSUE TITLE
Move PegJS compilation to webpack

### ISSUE THREAD

**Issue by pklaschka** [server-state/linux-raid-module#1]
Move compilation to `npm run build` via a webpack plugin, e.g., https://www.npmjs.com/package/pegjs-loader, and import it directly. This allows for easy iteration, compilation and maintainability.

**Comment by fussel178** [comment]
Nice idea. I will take a look :)

**Comment by fussel178** [comment]
Fix in current commit to develop branch: f08ca468c8fd5594d71b725bcd06771649935b12
