### ISSUE TITLE
Default options get overwrittten due to Object.assign

### ISSUE THREAD

**Issue by pklaschka** [server-state/linux-raid-module#12]
In https://github.com/server-state/linux-raid-module/blob/8dec7261202767196f491dbb85ccab7ff59f882b/src/index.js#L32

the `defaultOptions` get overwritten, as the empty object as first argument in `Object.assign` is missing. This could get solved with something along the lines of

```js
options = Object.assign({}, defaultOptions, options); 
```

**Comment by fussel178** [comment]
Fixed with commit b4dd8c7e3f9ec43d3e984f0e759d2bbf5aee2634
